### ISSUE TITLE
Add decoy flares on air assets

### ISSUE THREAD

**Issue by redblack20097** [UncreatedStaff/UncreatedWarfare#100]
it would be cool if the pilot could deploy (like the smokes in tanks) decoy flairs which throw off anti airs. and it wouldn't be that op cuz the pilot will have to switch through missiles and flairs (i guess you could use the flairs while your co is bombing or something).

**Comment by HamzaXSniper** [comment]
Have you ever played the server or are you just trolling?

**Comment by redblack20097** [comment]
> Have you ever played the server or are you just trolling?

silence

**Comment by HamzaXSniper** [comment]
There is already a flare mechanic implemented that has a 15 second cooldown which distracts Ground to air missiles and Air to air missiles, Which you would know if you had 17 braincells.

**Comment by redblack20097** [comment]
> There is already a flare mechanic implemented that has a 15 second cooldown which distracts Ground to air missiles and Air to air missiles, Which you would know if you had 17 braincells.

maybe thats new¿ i havent played for 2 months, or, yes i lack braincells.

**Comment by HamzaXSniper** [comment]
It has existed since the begin of season 2.

**Comment by Kazumiiiiiiiiii** [comment]
Flares were first mentioned in the server 6 months and 2 days ago, and I think (?) implemented 5 months ago :)
istg 90% of all issues in the server will be fixed if people just read the signs at main lmao
(and also the large red prompt with the loud alarm that pops up when you get locked on by AA)

**Comment by redblack20097** [comment]
I saw Top Gun and the flairs looked cool, i apologize, please stop bullying me, thank you.

**Comment by hat69420** [comment]
haha bullying go brrrrrrrrrrr

**Comment by hat69420** [comment]
for legal reasons thats a joke

**Comment by DanielWillett** [comment]
Already implemented

**Comment by Kazumiiiiiiiiii** [comment]
> I saw Top Gun and the flairs looked cool, i apologize, please stop bullying me, thank you.

L + ratio 
also, they are spelled "flares" not flairs lmao 
maybe google something before you suggest it <3

**Comment by redblack20097** [comment]
> > I saw Top Gun and the flairs looked cool, i apologize, please stop bullying me, thank you.
> 
> L + ratio 
> also, they are spelled "flares" not flairs lmao 
> maybe google something before you suggest it <3

okay dad

**Comment by Kazumiiiiiiiiii** [comment]
> 

call me daddy and I'll tuck you in tonight :D

**Comment by Pepenas** [comment]
> keep yourself safe thing night

**Comment by hat69420** [comment]
call 112 and ill put you in jail tonight ;)

**Comment by redblack20097** [comment]
> call 112 and ill put you in jail tonight ;)
> 

its not 112 in my country (and why are people still commenting on this?)
