### ISSUE TITLE
Enable 3rd Person POV for SU and F15 Co-Pilots

### ISSUE THREAD

**Issue by TrooperRI** [UncreatedStaff/UncreatedWarfare#101]
In a dogfight, the co-pilot would assist the pilot by providing information above and below the aircraft. The pilot is able to go into 3rd Person POV, but it is better for the pilot focus on fighting against another aircraft. 

Giving the co-pilot 3rd person POV extends the capabilities of its capabilities greatly. This allows more teamwork between the co-pilot and the pilot.

**Comment by s-worce** [comment]
Not possible afaik also commit teamwork with your JTAC/CCT aka anyone with squad lead.

**Comment by UsernameIsUnavailible** [comment]
Unturned does not support (as far as I know) to enable 3rd person for passengers, its Driver or/and regular 3rd person. (whenever you walk)

**Comment by DanielWillett** [comment]
Not possible.
