### ISSUE TITLE
Ear plugs

### ISSUE THREAD

**Issue by redblack20097** [UncreatedStaff/UncreatedWarfare#104]
(don't know if its possible tho) You know when your in a tank or something and you have to scream to the top of your lungs to communicate? so what if you add ear plugs like in arma so the vehicles arent loud af when you wear them or toggle them (wearing them would be cooler)

**Comment by redblack20097** [comment]
also make it so you can't hear hamza when you wear them

**Comment by Nama023** [comment]
![image](https://user-images.githubusercontent.com/51142304/187649829-019668b3-45f8-4d08-af91-a3ecd233752a.png)

You can turn down the volume of the engine by editing preferences btw

**Comment by redblack20097** [comment]
> ![image](https://user-images.githubusercontent.com/51142304/187649829-019668b3-45f8-4d08-af91-a3ecd233752a.png)
> 
> You can turn down the volume of the engine by editing preferences btw

i was just about the edit that. ik you can do that but thats gay cuz sometimes you do wanna hear them and youll have to leave the game every time to change it

**Comment by ToastyTimeZ** [comment]
> > ![image](https://user-images.githubusercontent.com/51142304/187649829-019668b3-45f8-4d08-af91-a3ecd233752a.png)
> > You can turn down the volume of the engine by editing preferences btw
> 
> i was just about to edit that. ik you can do that but thats gay cuz sometimes you do wanna hear them and youll have to leave the game every time you want to change it

Dude just stop making bad ideas use discord, you have the capability of doing so and if it comes down to it use a steam call or smth stop making crap ideas

**Comment by redblack20097** [comment]
Dude just stop making bad ideas use discord, you have the capability of doing so and if it comes down to it use a steam call or smth stop making crap ideas

could you stop replying to everything i say?

**Comment by ToastyTimeZ** [comment]
> > > > ! Dude just stop making bad ideas use discord, you have the capability of doing so and if it comes down to it use a steam call or smth stop making crap ideas
> 
> could you stop replying to everything i say?

Dude I don't reply to everything you say, and if I somehow do that then maybe it's because you do things like make the idea of earplugs in unturned, no it's not going to freaking work and, no there is no reason to add them even if there were

**Comment by hat69420** [comment]
i agree with toast

**Comment by benvalkin** [comment]
Not possible in Unturned.

**Comment by DanielWillett** [comment]
It would be possible to make vc louder

**Comment by hat69420** [comment]
> It would be possible to make vc louder

i would love that
