### ISSUE TITLE
Suggestion for the next season (Sorry for my bad English) 

### ISSUE THREAD

**Issue by LeonardoSerato** [UncreatedStaff/UncreatedWarfare#108]
My suggestion for the next season is a flatter map as the game is based on the squad game and make separate cities/monuments(not big cities, its better keep it balanced)  and not put everything together at one point of the map. ;)

**Comment by benvalkin** [comment]
Have you played squad? Half of the desert maps are made like Aqaba

**Comment by Sgtlog123** [comment]
Hmm..
Is it possible to make leveling up in ss3 feel more rewarding like ss1
Because leveling up in season 1 unlock new kit to player.
not just making fob and wait for C

**Comment by ToastyTimeZ** [comment]
> Hmm.. Is it possible to make leveling up in ss3 feel more rewarding like ss1 Because leveling up in season 1 unlock new kit to player. not just making fob and wait for C

They'll probably be adding the system they were tesing in beta S2 where each division will be leveled up individualy meaning, airforce, armored, and infantry will all be 3 different things that need to be leveled up individualy
