### ISSUE TITLE
Gamemode suggestion

### ISSUE THREAD

**Issue by Bencce85** [UncreatedStaff/UncreatedWarfare#114]
This is just a "would be cool" thing becasue i assume some of it is not even possible, or takes too much time to do, but it would be cool to have a gamemode like air supperiority, or a gamemode where air vehicles are available from the start and instead of 1 of each attackheli/jet there should be like 10-15, like a large themed battle, everything else is the same so there are infantry and armoured vehicles but again buffed in numbers. Also allowing solo jets, attack helis. So a larger scale battle mainly focused on vehicles, the respawn timers decreased, and the ammunition stack increased, with also the health of the vehicles increased. I think this would create a battlefield like gameplay, and more players can have fun with the air vehicles or tanks, so they dont need to wait for a tank/jet just to be taken from then etc... It would make this server much more enjoyable, becasue if the teamwork is not there, the lack of fobs, rallypoints, due to this vehicles, the team will just wait at base for an easier way to make it to the objective etc... Overall just a larger scale battle. But again this is just some random idea, i wouldn't be suprised if you needed a different server for this.

**Comment by UsernameIsUnavailible** [comment]
Cool concept, Poor execution guarranteed.
Not every player is a good pilot (cough cough Kampsie) and making a dedicated gamemode to only allow airplanes just calls for trouble.
Adding 10-15 jets per team would require a mayor revamp to the entire mains of each team. Making them look either hidious or unrealistic. Especially if its a different gamemode and you see that half your main is occupied by a runway..

Solo jets & attack helis is a no,
Respawn decreased is a no,
Ammunition stack increased would require the devs making extra items, no...
Health of vehicles increased calls for stupid encounters

At this point go play WarThunder air arcade battles...

**Comment by dukwilson88** [comment]
would be cool if we had a variant of games that either had no air assets or no armored assets or both

**Comment by DanielWillett** [comment]
Similar to #19
