### ISSUE TITLE
Remove taking damage while you are in armored and/or air assets

### ISSUE THREAD

**Issue by dukwilson88** [UncreatedStaff/UncreatedWarfare#115]
Due to Unturned having a bruh moment, you can sometimes get sniped by other players while you are in fully covered/protected vehicles such as tanks and jets. Every vehicle has this problem and it isn't unique to Uncreated either. There are plugins that check the ID of the vehicle you are in and if you take damage, it either reduces or nullifies it. We've had to cope with this bug since season 0, and it really doesn't seem like it would take a long time or be complicated to make.

**Comment by ToastyTimeZ** [comment]
Yeah Abrams tank is probably most noticeable you can shoot the driver out if you aim at the right spot, with transport heli's the feet of the pilot can get shot, with the Jet's and AH's the thinner glass meant to be where the pilot views through can be shot through

**Comment by ToastyTimeZ** [comment]
The Jet and AH problem though seems fair tbh

**Comment by UsernameIsUnavailible** [comment]
No, All vehicles' drivers shouldn't be able to get shot out if he is fully protected (e.g excluding Mi-8 & Blackhawk since sides are open).

**Comment by ToastyTimeZ** [comment]
> No, All vehicles' drivers shouldn't be able to get shot out if he is fully protected (e.g excluding Mi-8 & Blackhawk since sides are open).

Ik what I'm saying is it's fair that AH and Jet pilots can be shot out

**Comment by UsernameIsUnavailible** [comment]
Its not fair but ok LOL

**Comment by ToastyTimeZ** [comment]
> Its not fair but ok LOL

You act like I mean them getting shot lut by infantry, nah I mean stuff like armored vehicles HE killing them or when the co pilot of one heli kills the pilots of the other heli
