### ISSUE TITLE
Optional bombs

### ISSUE THREAD

**Issue by ToastyTimeZ** [UncreatedStaff/UncreatedWarfare#116]
It'd be interesting to see an option of bombs for jet's maybe smaller bombs but more in 1 drop, a capability of adding a napalm, it's for sure possible it's been done with the acid gun for Belgium curated map, and there's someone who even made a gas nade that caused the deadzone effect, and another for tear gas that works, I could be able to find someone willing to help make the more advanced napalm, but other than that it'd be cool to see different bomb loads.

**Comment by UsernameIsUnavailible** [comment]
Air assets are already OP enough.

**Comment by ToastyTimeZ** [comment]
> Air assets are already OP enough.

Then balance them? Tf? We've offered so many ways to balance shit out, and how would different kinds of bomb sets make it op? Small bombs- small radius less dmg to structures and vehicles, more quantity, basically for fighting infantry. Larger bombs, like the normal bombs we got right now sort of-anti vehicle, anti structure,5 each. How would that be OP?

**Comment by UsernameIsUnavailible** [comment]
we'll balance them, By not adding it :trollface:

**Comment by ToastyTimeZ** [comment]
> we'll balance them, By not adding it :trollface:

You are map dev, I'll wait for someone else's opinion, plus they aren't OP, we already have the Capability of using AA, guided missiles, and even tanks to kill them, it's the players if anything that would lead to any example of them being "OP", in which case add a new sign that says use AA to shoot air assets down, or just a sign showing how you can place a fob radio and build AA with no fob etc.

**Comment by UsernameIsUnavailible** [comment]
ok toast 🤓

**Comment by ToastyTimeZ** [comment]
> ok toast 🤓

Thx for agreeing, but next time remember there's no need for you to include a selfie 🥱

**Comment by UsernameIsUnavailible** [comment]
> 

Atleast GitHub supports the file size of my Selfie, Damn every fat layer you got requires an additional 50GB's

**Comment by ToastyTimeZ** [comment]
![Uploading 20220823_230518.jpg…]()

**Comment by ToastyTimeZ** [comment]
Well it seems it doesn't allow images at all, sooooo

**Comment by UsernameIsUnavailible** [comment]
https://user-images.githubusercontent.com/101991669/194730651-2fee4ea4-7d98-4030-a3b6-3949314118cb.mp4

I think it does

**Comment by ToastyTimeZ** [comment]
Uploading Fartnize.mp4…
