### ISSUE TITLE
New Premium Kit Suggestions

### ISSUE THREAD

**Issue by LimJunbak** [UncreatedStaff/UncreatedWarfare#139]
South and North Korean premium kits and guns.
South Korea usually sends ROK ARMY or ROKMC Units for humanitarian aid or protecting/aiding contractors who are of korean nationality. Whilst the North helps terroristic factions and regularly sends troops to help destabilize the country and start terror against any democratic country's military.

**Comment by ToastyTimeZ** [comment]
🤓

**Comment by benvalkin** [comment]
We don't have time for this as it would require the making of too many limited-use new clothes and weapons.
