### ISSUE TITLE
Action Menu

### ISSUE THREAD

**Issue by IlosdVay** [UncreatedStaff/UncreatedWarfare#14]
There was a suggestion on Discord to implement a menu in-game, what looks like the default unturned emote menu (the one pressing C) 
![kép](https://user-images.githubusercontent.com/109554716/179615905-1a9edf4b-ffd2-499d-8cfd-da0296804b8b.png)
My idea, ripped off from a battlefield game
Pressing on of them would show a corresponding icon above your character (for instance - an ammo icon for requesting ammo). It would be there for 7 seconds, and it would have a cooldown too! Also, it should show a message in the chat. 
My question is, would we able to get this for season 3? As it would help a lot and would add a new layer of teamwork to the game.

**Comment by benvalkin** [comment]
I think we should definitely add this for next season actually. It could work by pressing ',' or '.' to open the UI, which goes away once you click a request or remains for 5 seconds. We could easily make it very useful with the following options:

- Thank you
- Sorry
- Request pickup - notifies vehicle drivers to pick you up
- Request medic - notifies nearby medics
- Request ammo - notifies nearby riflemen
- Request reinforcements - notifies nearby teammates

For squadleaders, we could also have a special 'Tactical' button that opens a new menu with the following options:
- Request supplies(squadleader only) - notifies all active heli pilots to help you build a FOB at your location
- Request transport (squadleader only) - notifies all active heli pilots to come pick your squad up
- Request airstrike (squadleaders only) - notifies all jet pilots to strike your marker
- Request UAV (if commander is added) - notifies commander to authorize UAV on your marker
- Request artillery (if commander is added) - notifies commander to authorize an artillery strike on your marker

and also an 'Orders' button with some more squadleader options:
- Attack
- Defend
- Move

My only concern is that it might be annoying if players have to stand still while the UI is up.
