### ISSUE TITLE
We need more medics.

### ISSUE THREAD

**Issue by HamzaXSniper** [UncreatedStaff/UncreatedWarfare#143]
The kits are honestly great (on both teams) but people are still not using them, Here are some ideas to encourage the use of the kits:
1- Passive exp to medics (same idea as exp for /duty) but to make sure its not abused a check would be made to make sure the players are not afk in main and they are actually out doing something ( maybe check if someone was healed every 5 minutes) and if they have taken damage/died/damaged someone/ killed someone, basically to check if they are fighting. 
2- Increase the amount of exp given to players, currently its 4 credits per heal but i believe it should be something like 10.
3- There always remains the buff of medic kits which might do some good? Perhaps giving different and better armor would make it more popular. But people might just start using it as a tank kit.
4- If somehow skills can be increased for the time the person is using the medic kit (notably the healer one to make them more effective) But there needs to be something to make sure the skills are reverted after the kit is unequipped so someone doesn't just take the medic kit and 2 minutes later take some other kits and the skills remain.

There must be more ideas that am missing so please reply with anything or if you disagree about something.

**Comment by IlosdVay** [comment]
Or just make downing suicide available after 5 seconds you downed? Players might hate it for a bit, but medics will have greater use then... Some suicide even if there is a medic.

**Comment by benvalkin** [comment]
We can add a timer of say 10 seconds until you can give up - another thing that might help is making it slightly harder to finished off downed enemies
