### ISSUE TITLE
Better transport, better gameplay.

### ISSUE THREAD

**Issue by DeathFromAbove145** [UncreatedStaff/UncreatedWarfare#153]
I suggest for S3 to introduce more reliable transport methods for players.
Alot of players like to roam around and scout for fobs, vehicles or rush into a place. They use humvees or transport trucks for this, which in my opinion is a WASTE OF ASSET, since they're abandoned on the field later and noone bothers to RTB them. 
We can introduce 1-2 seater ATVs instead. Better for players who want to just rush into an area but they have no fob closeby, and better for scouting around, and it wouldn't be a big waste to let it rot in the battlefield either.

**Comment by HamzaXSniper** [comment]
I love this idea, Having a fast yet open vehicle would be the perfect vehicle for those who would be scouting. If this were to be added it needs to be time locked for the first minute to counter players taking it and rushing the enemy's first cap.

**Comment by DeathFromAbove145** [comment]
> I love this idea, Having a fast yet open vehicle would be the perfect vehicle for those who would be scouting. If this were to be added it needs to be time locked for the first minute to counter players taking it and rushing the enemy's first cap.

Exactly. We can nerf it a little bit by the 1 minute timing. One might say "It's not balanced since it's too fast to be shot by AT or TOWs" but they can't forget that a normal player with a rifle can take down the ATV driver easily. This is merely for scouting

**Comment by benvalkin** [comment]
I don't really want the game to filled with people riding around on fast ATVs but all vehicles are supposed to respawn when abandoned... is it perhaps a bug that they aren't?

**Comment by DeathFromAbove145** [comment]
They do respawn but it takes time when abandoned. You could limit ATVs to two only and it would be enough to support the team, two is enough so it's not everyone going around using them, and maybe setting a little restriction to who can use it and when, sounds fair for what it gives the team.
