### ISSUE TITLE
Broken Laser Guided Missiles

### ISSUE THREAD

**Issue by benvalkin** [UncreatedStaff/UncreatedWarfare#155]
People have been complaining about jet laser guided missiles not tracking for a few months, need to investigate

**Comment by AngelAbov3** [comment]
From testing what we can tell is that when firing on a laser designated emplacement LGM's fire from the bottom middle of the jet are invisible and do not track with your mouse. 

This fixes with the restart of the server but can also break again...

if the enemy team has your own team emplacements marked
You do not even need to fire directly at the emplacement you just need to fire in any direction when an emplacement is marked on either team

**Comment by benvalkin** [comment]
@AngelAbov3 does it ever happen that after some point in time all LGMs fired become invisible and don't track?

**Comment by AngelAbov3** [comment]
I don't exactly understand what you mean but after firing on 1 marked emplacement LGM's are bugged till restart

**Comment by benvalkin** [comment]
@AngelAbov3 So if I understand you correctly, the bug starts happening after an enemy SL spots your own team's emplacement, and you then try to to lock onto it with a jet. After this happens, all LGMs are broken, and the server must be restarted to fix them.

**Comment by AngelAbov3** [comment]
> @AngelAbov3 So if I understand you correctly, the bug starts happening after an enemy SL spots your own team's emplacement, and you then try to to lock onto it with a jet. After this happens, all LGMs are broken, and the server must be restarted to fix them.

You are correct and your own team marking and firing on enemy emplacements also "triggers" the bug

**Comment by benvalkin** [comment]
I'm having trouble recreating this on the main branch for next season right now, so I think blazing might have fixed it at some point I'm going to mark this as done for now.

I did however fix a null reference exception being thrown when a player fires a LGM and leaves the server - but this didn't seem to break anything.
