### ISSUE TITLE
Suggestion - Losing Tickets Once A Fob Radio Has Burnt Out

### ISSUE THREAD

**Issue by AngelAbov3** [UncreatedStaff/UncreatedWarfare#160]
Currently destroying a fob has no real impact on the team that loses the fob apart from losing ground and this sometimes doesn't even happen because backup fobs are built. 

With this being said an interesting idea would be to have ticket loss (around 25 - 30ish tickets per radio) when a fob radio burns out after being destroyed. 

- This would put an incentive on properly protecting fobs.

- Get more people to use breacher / combat engineer for it's intended purpose not just for a gun, it would also help breacher / combat engineer if credits and exp for destroying a fob was fixed.

- These changes would also help the server when it's low population finish invasion matches faster and not cause 5-6.5 hour games with people just spam placing bad unprotected fobs.

**Comment by benvalkin** [comment]
FOB radios will now cause a loss of 40 tickets when destroyed. Feedback on this amount choice will be appreciated since it might be quite high

**Comment by UsernameIsUnavailible** [comment]
bruh if we only get a total of 300 tickets, 40 per radio is ridicilous.

**Comment by Pepenas** [comment]
add more tickets

**Comment by AngelAbov3** [comment]
Couple things about this

- Is this in the official server?

- With a starting amount of 200-300 tickets 40 per loss might be quite high

- A few bugs you may want to look into. 
Tick speed being extremely fast causing radio's to burn out really fast.
If a radio is placed on and angle or in a weird position when destroyed while bleeding out radio will be invisible and also the burning "icon" sometimes wont show.

**Comment by benvalkin** [comment]
@AngelAbov3 This feature is not on the production server, it will be included next season. We can maybe change the loss to 30-35.

Could you open a separate issue about the fob tick speed?
