### ISSUE TITLE
Destroying fobs and proxy through floors

### ISSUE THREAD

**Issue by AngelAbov3** [UncreatedStaff/UncreatedWarfare#165]
This is a small ish issue making you able to destroy fobs and proxy from under the floor

- If the bunker or radio is raised above the floor and it doesn't poke through the ground it cannot be destroyed but...
- Even if the bunker/radio is raised it can still be proxied.

https://user-images.githubusercontent.com/123339655/218787259-42d741bd-1ae0-4c9c-a385-ef2e8eb397f5.mp4

**Comment by DeathFromAbove145** [comment]
This is an issue i actually was about to bring up because it really sucks fortifying your fob in areas like wind HQ floor 3, just for an enemy to blow it up with the help of a small opening and this bug.

**Comment by ToastyTimeZ** [comment]
Hm fake hit boxes exist on vehicles, so I wonder if you could perhaps make a fake hitbox on some things like that to stop such situations, if this isn't capable of being fixed there is some things that you can do to avoid this, you can place a different structure on the ground and build fob on it then remove the bottom, you can build walls on a thin roof above a fob to stop mortar splash from hitting it through, all in all even if they get rid of the bottom bit, unturned is funky and explosions sometimes have a hard to with cooperating with both map structures and player barricades, for player barricades explosions simply can only splash so far so if you build enough surrounding a fob it'll stop splash entirely.

**Comment by DanielWillett** [comment]
Todo: linecast from point of explosive to structure origin to check for floors.
