### ISSUE TITLE
Add More Rows to End of Game Leaderboard

### ISSUE THREAD

**Issue by WoeiSiesta** [UncreatedStaff/UncreatedWarfare#169]

**Comment by WoeiSiesta** [comment]
The player stats does not show up in the end game leaderboard if u are not the top 10-15 player with the highest exp on the current match.

**Comment by benvalkin** [comment]
This is kinda intentional as there's just not enough space for more than 15 rows on the screen... We just decided that it should be only the top 15 players who get featured.

We could try add a scrollable view at some point, but for now this is low priority.

**Comment by DanielWillett** [comment]
We can't add a scroll box because to scroll you need the mouse and you can't use chat when you have the mouse on your screen.
