### ISSUE TITLE
Crewmen and pilots getting shot out of their vehicles.

### ISSUE THREAD

**Issue by dukwilson88** [UncreatedStaff/UncreatedWarfare#197]
This has been a problem since Fools Road. Due to some Unturned spaghetti fuckery, armor crew can be damaged and killed while they are still inside their vehicles. Other servers have fixed this with a plugin that checks the ID of the vehicle you are in and then either reduces or removes the damage taken. This would only apply to APCs, IFVs, MBTs, jets and attack helicopters.

**Comment by DanielWillett** [comment]
This was fixed.
