### ISSUE TITLE
Highlight Locations Colors

### ISSUE THREAD

**Issue by BusterBarnes** [UncreatedStaff/UncreatedWarfare#212]
Make the color of locations on the map a different color from white so they are distinct from all the player names, that way you can see what the point on a map is with a bunch of people crowded around it.

**Comment by DeathFromAbove145** [comment]
This is good for newer players who haven't learnt the names yet, it does take a week to remember routes and all, i support this.

**Comment by benvalkin** [comment]
This is not possible, unless I'm missing something. Are map location names able to be forced to be a different colour from white?
