### ISSUE TITLE
Vehicles And AT

### ISSUE THREAD

**Issue by AngelAbov3** [UncreatedStaff/UncreatedWarfare#238]
Sat on some of this for a while and have not seen a stone move so here we go.

There have been complaints about air and armored vehicles some of the following might help to fix some of the issues. 

**(DISCLAMER)** This is mainly directed towards infantry gameplay since it's currently extremely miserable but I will try and balance it out.

 ### Anti Tank 

**Hat and LAT Rework (An addition of more rockets to the AT kits has been ok'd by 420)**

>LAT 1 | This kit would stay the same but include 1 extra heat rocket (this would be the base for lat customs)

>LAT 2 | This kit  would include 1 heat 1 tandem  (This would be the extra lat weapon point on customs)

>HAT 1 | This kit would would include 2 heats 1 tandem (This would be the base for hat customs)

**Rockets and Vehicle damage** 

Since the addition of vehicle weak and strong points yes this is a thing now,  server lag/desync and how the vehicle hit boxes work. 
HEAT and Tandem is not guarantied 1 shot kill anymore on some of the vehicles they are meant to 1 shot. 
A few things have been suggested for this

>Buffing overall rocket damage and decreasing overall vehicle hp slightly

>Increasing the size of the origin points on vehicles (Unsure on how this completely works someone clarify for me)

>Making RPG's use a bullet instead of a projectile (Unsure if this can be done and is mainly for server lag/desync issues)

### Vehicle amounts and timers and ticket cost

This would help the with the current "vehicle spam"

>Humvees | Able to be requested at the start of the game 
(2 Vehicle pads with a 5 minute respawn timer cost 10 tickets)

>APCs | Able to be requested 5m after the game has started
( 2 Vehicle pads with a 7:30m respawn timer cost 20 tickets)

>IFVs | Able to be requested 7:30m after the game has started
( 1 Vehicle pad with a 10m respawn timer cost 25 tickets)
 

>MBTs | Able to be requested after 10m after the game has started
( 2 Vehicle pads with a 15m respawn timer 30 tickets)

>Attack helis | Able to be requested 15 minutes after the game started
(15 minute respawn timer cost 35 tickets)

>A2A and CAS Jets | Able to to be requested 25 minutes after the game started
(20 minute respawn timer cost 35 tickets)

### Emplacements

>ATGMs
Decrease damage to 900 (old Bradly tow damage)
Maximum range of 800 meters

>AAs
Increased horizontal range to 850 meters or higher. (This is practically a large map 550 is to short considering the speed of the jets and the ramp up time
Shortened ramp up time  (would require a bit of testing since idk the current ramp up time)

**Transport helicopters** 
I'm not a fan of the new transport helis and think they need some adjusting they also ruin some gamemodes

>Decreased speed to 125mph
>Recoil on the guns
>Decreased damage making them unable to 1 shot head shot 
>Decreased mag size
>Decreased fire rate on the NH90 Guns

**Comment by Pepenas** [comment]
The reworks of the mounted guns on the trans heli dont think is that needed plus how come the same gun that can be held by infantry dont do same damage as the one on the heli bad take.
And the ATs rockets be bullets i dont think that will work it wont show the rocket trials and all maybe even the velocity and trajectory will be fucked as well also who hierd you angel this takes are caca!

**Comment by AngelAbov3** [comment]
Forgot to add a 2 things

>Increase elevation/depression on every armored vehicle
>Increase breaking power on every armored vehicle

**Comment by AngelAbov3** [comment]
> The reworks of the mounted guns on the trans heli don't think is that needed plus how come the same gun that can be held by infantry don't do same damage as the one on the heli bad take.


Aint gonna lie that ^ don't make sense to me rn but...

V_MG3

Player_Damage 65
Player_Leg_Multiplier 0.3 = 19.5
Player_Arm_Multiplier 0.25 = 16.25
Player_Spine_Multiplier 0.85 = 55.25
Player_Skull_Multiplier 1.69 = 109.85

MG3

Player_Damage 65
Player_Leg_Multiplier 0.3 = 19.5
Player_Arm_Multiplier 0.25 = 16.25
Player_Spine_Multiplier 1.00 = 65
Player_Skull_Multiplier 1.28 = 83.2


So a 2 fire rate 100rnd LMG with the ability to take 1200rnds, capable of 1 shot headshotting and moves 200ish mph is fine? Is what I'm looking at???

**Comment by Pepenas** [comment]
> So a 2 fire rate 100rnd LMG with the ability to take 1200rnds, capable of 1 shot headshotting and moves 200ish mph is fine? Is what I'm looking at???

yes
