### ISSUE TITLE
Game mode - Flare Domination

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [UncreatedStaff/UncreatedWarfare#25]
3 or more points on map, Capturing it takes X seconds (fast cap) & team has to hold area. Each captured area (if you can hold it) drains X tickets per X minute.

**Comment by HamzaXSniper** [comment]
Isnt that invasion with extra draining?

**Comment by UsernameIsUnavailible** [comment]
@HamzaXSniper 

Not really, Flare domination requires you to hold the zones & defend, All three (or more) can be attacked (not like Invasion, where you need to attack points in a specific way)

**Comment by HamzaXSniper** [comment]
Give them zones and they dont have to capture it in a specific order?

**Comment by UsernameIsUnavailible** [comment]
Basically, Three zones you have to capture & hold. Each zone drains X tickets from enemy team. Minimum cap required is 2 out of 3 to win (eventually)

**Comment by benvalkin** [comment]
This is the same as the Conquest game mode that is already planned (there are 3-4 objectives on the map that can be captured in any order. While your team holds the majority of objectives, the enemy team is put on a bleed)
