### ISSUE TITLE
my game giving this error i deleted game and redownloaded but still giving

### ISSUE THREAD

**Issue by nabersin23** [UncreatedStaff/UncreatedWarfare#266]
Client and server disagree on asset "C-4 4-Pack Charge" configuration. (File: "IED_C4_4pack" ID: 85bcbd5ee63d49c19c3c86b4e0d115d6)
Usually this means the files are different versions in which case updating the client and server might fix it.
Alternatively the file may have been corrupted, locally modified, or modified on the server.
Client hash is 9A727E25D129AF62DB7DF95185F50CCF59E29317, whereas server hash is F93B25FCD3F2D0FC0FB006A39E405A7F736482F7.
Client and server agree this asset is from Workshop File "Uncreated Content" (2839462324).

**Comment by DanielWillett** [comment]
![image](https://github.com/UncreatedStaff/UncreatedWarfare/assets/12886600/25e1d388-e04a-4b42-b0d2-b45e0eebdc8a)
You can try unchecking all your mods in Workshop > Manage except Gulf of Aqaba and restarting but this is a recent Unturned bug.
Some people have found success by changing their system language to `English (United States)`.
