### ISSUE TITLE
Insurgency Cache Damage Filter

### ISSUE THREAD

**Issue by AngelAbov3** [UncreatedStaff/UncreatedWarfare#267]
Can't find the original discussion but this was deemed doable I think.

Insurgency Damage Filter.

Can do Damage.
- Breaching Charges.
- RPGs (I think we said yes to this idk).

Can't do Damage.
- Mortars.
- Landmines
- Ground Vehicles.
- Air Vehicles.

**Comment by realtrollman2319** [comment]
a way you can do this thing is:
```cs
Guid mortarGunGuid = new Guid("d6424d034309417dbc5f17814af905a8");
if (pl.player.equipment.asset.GUID == mortarGunGuid)
{
    shouldAllow = false;
    return;
}
```
inside `EventFunctions`' `OnBarricadeDamaged` method

**Comment by DanielWillett** [comment]
That doesn't work because the player can get off the mortar in between the time it's launched and hits. We have a way to track projectiles origins which we use for death messages.

**Comment by realtrollman2319** [comment]
I see, thanks for letting me know it won't work

> That doesn't work because the player can get off the mortar in between the time it's launched and hits. We have a way to track projectiles origins which we use for death messages.
