### ISSUE TITLE
[suggestion] Radios and Frequencies

### ISSUE THREAD

**Issue by ElexDavina** [UncreatedStaff/UncreatedWarfare#42]
Make it so when you join a group, you're forced into a set frequency. Not sure if it's possible to prevent players from changing their own frequencies but that would be best.
Would probably require a new handheld radio model since the vanilla walkie talkie looks goofy af. Also not sure if this is possible, but if the helmets could function as an earpiece that would be really nice, so we dont have to add an earpiece to every kit. 
Mic spam wouldn't be an issue as we have the /mute voice command now.

**Comment by DanielWillett** [comment]
Helmets can't be earpieces as they're a different clothing slot but its possible yeah

**Comment by SunShine214** [comment]
Maybe the set frequency would be your squad?

**Comment by benvalkin** [comment]
I'm not a fan of a squadleader radio chat feature because I don't think it will be used, especially if it's an item that you have to take out. I'm going to close this for now but maybe we can find a use for a radio chat feature at a different time
