### ISSUE TITLE
New helicopter mechanics

### ISSUE THREAD

**Issue by Kampsie3** [UncreatedStaff/UncreatedWarfare#44]
ik yall making some updates to airforce for the season 3 so some new heli game mechanics would be cool...
Currently the 2 basic helicopters are really just transport and supplies which is more efficient with a logi and no one dose transport lets be honest /deploy fobX

Some new mechanics to the helis would be nice, such as giving the pilot the ability to see + where someones down, like a medic, (example of the use: pilot + combat medic doorgunner, lands and go rescue ppl) AND a hook, to recover lost, damaged, stuck, or unreachable vehicles, ofc this can be limited with a plugin like no picking up enemy vehicles and you can only grab vehicles that are marked as 'IDLE'

I think this would make the heli alot more useful than a inefficient logi truck with rotor blades
I really only find helis fun as im kinda a casual so this would be really cool to see in Season3

**Comment by Kampsie3** [comment]
I also want to add onto this, when you unity the helicopter please dont pitch the rotor 45*, it makes flying weird, hovering weird, and it looks weird in general
Either keep the rotor centered and have a good stable hover and 90* when flying, or make the rotor pitched down like 80* in unity and have no hover but good looks when flying
you gotta make up your mind or you'll have bad controls and look weird and cant hover properly

**Comment by benvalkin** [comment]
I think pilots being able to see downed players/idle vehicles is a bit pointless, but with the Action Menu transport heli pilots will definitely be able to see requests for where to pickup and drop squads, as well as where to deliver supplies.
