### ISSUE TITLE
Abandon vehicles

### ISSUE THREAD

**Issue by Kampsie3** [UncreatedStaff/UncreatedWarfare#45]
You already own a vehicle, but you want to request a different one, what do you do? well you gotta loose it, so either crash it or get it blown up by enemy. Add a /abandon command, Look at a vehicle you own... /abandon... its not yours anymore, go request a new vehicle!

**Comment by DanielWillett** [comment]
Added feature to master branch.

**Comment by Kampsie3** [comment]
epic
