### ISSUE TITLE
Supply Chain

### ISSUE THREAD

**Issue by Kampsie3** [UncreatedStaff/UncreatedWarfare#51]
This may be complecated, BUT, will be very useful for logistics to move supplies and ammo back and forth between FOBS who need them,
Oh your team just moved up a fob closer to the objective? Let's transfer the supplies/ammo from the most distant fob, to the closest!
Or you think a fob is about to fall to the enemy? Get the supplies and ammo out of there ASAP!

This can work by allowing pilots and squad leaders to Access the FOB RADIO, opening it will show you all the supplies/ammo, dropping it will put the supplies/ammo into the nearest logistics vehicle such as logi truck or heli

Effectively, this makes a much more efficient supply chain and makes sure supplies/ammo dont go to waste

**Comment by benvalkin** [comment]
We could make the /load command work when near fobs, that wouldn't be to hard

**Comment by Kampsie3** [comment]
cool!

**Comment by benvalkin** [comment]
Instead of a command, this will now be accomplished with buttons 'load/unload ammo/build' that show when you open the Action Menu inside a logi.
