### ISSUE TITLE
Share credits feature

### ISSUE THREAD

**Issue by Kampsie3** [UncreatedStaff/UncreatedWarfare#52]
I see a ton of people who have too many credits, in the thousands, and dont know what to spend it on, Well, You COULD use it to support your team who cannot afford stuff

/share credits 0 - 100   example: /share credits 50

Basically, what this dose is give your team a global amount of credits, anyone can use them!
Assuming someone is sharing 100 credits, and you buy a vehicle, the shared credits will be deducted instead of your own credits... how nice! :D

this would be nice for broke or new players and something to give away for people who have way too much and cant get rid of them

Ofc, from a developer standpoint if some HR just gave away hundreds of credits each round there wouldn't be a point to 'buying' stuff, so this could be limited (100 shares per player)

**Comment by DanielWillett** [comment]
I don't know about this one, I think it kinda defeats the 'progression' to get higher-rank kits and vehicles.
