### ISSUE TITLE
Kornet/Tow Re-balance

### ISSUE THREAD

**Issue by 3312bKarp** [UncreatedStaff/UncreatedWarfare#53]
Tows and Kornets are really powerful to the point where they can reliably hit and destroy most vehicles except attack helis and jets.
I propose a laser warning that would work similarly to the a2a missiles warning. (I know that tows arent laser guided but stfu nerd)
Basically, if a fired missile directly or closely targets an armored vehicle or an air vehicle then you get a warning just like aa.
Armored vehicles with smoke could get the same press / to pop smoke message as air vehicles with flares.
Skilled players could move the crosshair onto the target last second to avoid the warning.
The laser warning would trigger if the target is in this area of the scope while the missile is in the air.

![image](https://user-images.githubusercontent.com/109536648/180653442-fd55707c-fe4c-4d83-9448-3492ecc3761a.png)

**Comment by Entity645** [comment]
Possibly, in addition to this, the guiding could be capped at a certain distance as if the tow is wire guided

**Comment by Kampsie3** [comment]
Btw while this tow/kornet thing is here, Maybe not make kornet/tow 1 shot transport helis? there's a AA buildable for a reason... kinda fustrating when you just wanna do supply runs and get nailed by some random across the map

**Comment by Entity645** [comment]
Tows need a max control distance for sure.

**Comment by 3312bKarp** [comment]
Kampsie just don't fly in a straight line.
It's that simple **Especially** if the shooter is far away.

**Comment by benvalkin** [comment]
Maybe not a bad idea but I kind of want TOWs to be powerful... their disadvantages are that they're stationary and vulnerable and require effort to set up

**Comment by Kampsie3** [comment]
Maybe allow them to be damaged by normal guns? and the AA/mortar posts too, they are literally just projectiles on stands after all, no real armor on them
