### ISSUE TITLE
Npc that sells sandwiches

### ISSUE THREAD

**Issue by MissileMagnet01** [UncreatedStaff/UncreatedWarfare#54]
I wanna suggest an npc that sells cum sandwiches, if this has any problems with how the server works then make it so the sandwich that the npc sells dont have any effect on the players hunger bar.

**Comment by DanielWillett** [comment]
This is a very interesting suggestion, really makes you think, "What if we added a NPC that sells cum sandwiches?". Unfortunately I think it could cause a distraction to players and could be camped by the other team. It also doesn't fit in with the extreme realism we strive for here at Uncreated Network. Where does the vendor get the Cum Sandwiches from? He never leaves, never gets deliveries. How would the players pay the NPC? Ammo? They need that. Experience? Maybe but experience isn't really a currency. Money? There's no money to get. Unfortunately I don't think this feature will work out quite right, so I don't think we can add it. I'm sorry.
