### ISSUE TITLE
[suggestion]Adding a new feature for medics

### ISSUE THREAD

**Issue by MissileMagnet01** [UncreatedStaff/UncreatedWarfare#55]
I think its a good idea if medics were able to see or know their teammates health, not from afar though as to not obscure the players screen(or if there was a way to not to, that would be great), theres a thing in unturned where if u get close to another player or an ally you can see their names and stuff maybe you could put it there, or at least somewhere since it would be pretty weird for a medic to not be able to see their teammates being injured/having low health from up close.

**Comment by HamzaXSniper** [comment]
To add to this they also would be able to see the amount of meds in the person's inventory, which could help them disturbute the medical supplies as needed.

**Comment by Entity645** [comment]
Could perhaps be done with the current medic ui(the green healthcare icon)? Green is slightly damaged, yellow is heavily damaged and red is downed. Number of bandages in inventory in the middle of it. Would consist of 12 possible ui images

**Comment by DanielWillett** [comment]
Eh, the problem with those is to clear/move one you have to completely clear all of them and resend them. Having one for each player won't be very efficient. Maybe instead medics get a health bar on their squad menu and a count of meds.

**Comment by Entity645** [comment]
Perhaps a visual bleeding effect? I do not know if particules could be used here as a more efficient way of doing things.

**Comment by benvalkin** [comment]
I found a decent solution for this after starting the Action menu.

When you press "Need Medic", it will show a a flashing icon above your head for a 10 seconds that will be visible to all nearby medics. You will also be able to see a marker above nearby medics for the same duration. We can also make it gives medics XP if they heal someone who recently called for help. 

While this won't show your health, it will definitely help friendly medics see who's injured.

**Comment by UsernameIsUnavailible** [comment]
tbf medics should recieve more things to do or atleast better weapons in their kits, MEC has no medics at all since the guns are ass (no scopes)

**Comment by HamzaXSniper** [comment]
Or some sort of multiplier should be added to rewards of healing, since alot of the time there is only 1 medic to heal 19 friendlies and thus they should have a bonus for helping the team directly.

**Comment by benvalkin** [comment]
I think the new 'Need Medic' action menu button that raises a flashing icon above your head that medics can see will be sufficient enough to make medics actually useful. They shouldn't need to see your health, just that you are asking to be healed.

However, if knowing health turns out to be very helpful, we could make the flashing icon choose from 4 different icon variants for 100, 75, 50 and 25 HP intervals.

**Comment by HamzaXSniper** [comment]
A flashing icon should be set to show the medics who has the lowest health and to prioritize players, It would be made to speed up as their health decreases.

**Comment by benvalkin** [comment]
@HamzaXSniper I was thinking something like this when you call a medic?


![Image](https://user-images.githubusercontent.com/69928007/183980873-fe246e89-e3fd-40ec-a22d-aa84c4038738.png)

**Comment by HamzaXSniper** [comment]
The icons seem great but if there was a way to add a more quantifiable to prioritize healing.

**Comment by benvalkin** [comment]
I don't see why it should be more quantifiable. It just means two players with 24 hp and 49 hp get treated with the same priority. These icons will have to do as there's not any way we can add dynamic numbers or text to 3D effects.
