### ISSUE TITLE
Fortification limit (XP Farming fix)

### ISSUE THREAD

**Issue by DanielWillett** [UncreatedStaff/UncreatedWarfare#66]
Each player will have a cooldown for each player they revive (maybe 10-15 mins) so they can't revive, injure, revive, injure, etc to farm xp.

**Comment by HamzaXSniper** [comment]
Most people use emplacements to farm exp Example: making a fob at mec outpost and supplying it with 100 buildings and place hesco towers, And not reviving.

**Comment by HamzaXSniper** [comment]
The point am trying to reach is perhaps limiting exp from emplacements would be better, as adding a cooldown to exp from medic discourages people from getting medic and helping their team, To add as a medic you deal with the same players in a game which lasts around 30-40 minutes.

**Comment by Entity645** [comment]
Building xp should not be limited on objectives, same for medic in a currently in combat objective (Enemy team in the zone)

**Comment by DanielWillett** [comment]
I just mean per player so if I revive the same player twice in say 2 minutes I won't get XP from that.

**Comment by DanielWillett** [comment]
Trying to think of a good way to limit that, possibly what Entity said, but FOBs can be useful that aren't on objectives. Maybe add a limit to how much XP you can gain from a FOB. That would include delivering supplies, building, etc.

**Comment by HamzaXSniper** [comment]
I believe i have found an fix to the exp farming through fobs and other methods and have listed them below:-

**Firstly** After a certain limit supplies simply do not register i personally suggest 90 for multiple reasons listed below, ammo could reach any amount but wouldn't give ANY exp. And each player is only limited to 500 exp per hour(or game) gained from supplying fobs but it wouldn't limit deploying of teammates. 
**Secondly**, Shoveling buildables wouldn't give exp after 125 to stop players from building 20 hesco towers and gain hundreds of exp.  
**Thirdly** Even though i dont believe this is an actual issue but it was mentioned so here we go: it should NOT be made into a cooldown system, instead exp should stop to be given after healing the same player 3 times in a row and be limited for 15 minutes for that player only. So the same player doesnt get downed and revived time over time but it would still allow them to heal other players and gain exp from that.


Why 90 supplies: it accounts for the cost of 2 bunkers, 1 anti air emplacement, 1 atgm emplacement, machine gun emplacement, mortar emplacement and ammo box(es) and 10 extra for fortification. (15x2 + 15 + 15 + 7 + 10 + 3 + 10).

**Comment by benvalkin** [comment]
I am going to add a configurable limit to how many of each fortification can be placed on a FOB, this should fix a lot of XP farming since I believe the biggest cause is from spamming fortifications - this should also help prevent ridiculous indoor compact FOBs somewhat

**Comment by benvalkin** [comment]
A limit of 90 supplies could also be implemented easily
