### ISSUE TITLE
Vehecle audio changes

### ISSUE THREAD

**Issue by Entity645** [UncreatedStaff/UncreatedWarfare#67]
It would be worthwhile to see if it is possible to engineer the audio tracks of vehecles to not drown out player voices.

**Comment by benvalkin** [comment]
This is not something I can realistically do, also I already spend enough time and effort engineering audio tracks for guns and vehicles

**Comment by benvalkin** [comment]
This is not something I can realistically do, also I already spend enough time and effort engineering audio tracks for guns and vehicles

**Comment by benvalkin** [comment]
This is not something I can realistically do, also I already spend enough time and effort engineering audio tracks for guns and vehicles

**Comment by ToastyTimeZ** [comment]
> It would be worthwhile to see if it is possible to engineer the audio tracks of vehecles to not drown out player voices.

Pretty sure they'll try adding in the little walkie talkie system that they were experimenting with for a little bit during this season, that sort of helps, of course you can always just use discord btw then turn down master volume ingame. This all really just goes into a blame nelson for having voice chat volume and also master volume both affecting voice chat.

**Comment by DanielWillett** [comment]
One thing we could do is make voice chat louder when you're in a vehicle.

**Comment by ToastyTimeZ** [comment]
Nah just make every vehicle like the Tesla 90 :^)
