### ISSUE TITLE
customizing logistics payloads and buffing transport helis

### ISSUE THREAD

**Issue by 3312bKarp** [UncreatedStaff/UncreatedWarfare#68]
If you drop supplies from a truck/heli in main, said supplies are switched for the other type so ammo>builds>ammo.
that way you could customize your payload.

Make helis faster and/or have more space for supplies because now they aren't too good for supplies or transporting people.
People don't like to get transported in helis because of 
- Faq16# pilots but we can't fix them
- Helis are slower than deploying to a fob and then running
- And are easily shot down with ATGMs which is kind of stupid
And with their poor payload, a logi trucks are generally better for logistics which should not be the case.

**Comment by benvalkin** [comment]
This is already planned for next season, the new Action Menu will have a "Load/Unload Build/Ammo" option which should be what you're looking for. Also I'd like to potentially make helis a bit faster for next season (jets are already going to be fast af)
