### ISSUE TITLE
Better friendly mortar warnings, add a count-down and take height differences into account.

### ISSUE THREAD

**Issue by DanielWillett** [UncreatedStaff/UncreatedWarfare#69]

**Comment by HamzaXSniper** [comment]
69 👍

**Comment by benvalkin** [comment]
Is this really worth adding and testing? What's the issue with current mortar warnings?

**Comment by DanielWillett** [comment]
They can queue up for over a minute if multiple are shot at you at once, and they don't take height differences into account.

**Comment by DanielWillett** [comment]
This is done btw just need to polish the UI a little.
