### ISSUE TITLE
Remove transport trucks

### ISSUE THREAD

**Issue by 3312bKarp** [UncreatedStaff/UncreatedWarfare#79]
I suggest the transport trucks be replaced with one humvee and one logi truck because they are almost never used anyway, and an extra humvee for transport/fire support and an extra logi for building fobs would be much more useful. (especially logis since they are almost always all taken) Why cant they be merged with the logi trucks like in squad, there is almost no use for them.

**Comment by benvalkin** [comment]
I think for next season we're not going to have any transport truck spawns

**Comment by UsernameIsUnavailible** [comment]
> I think for next season we're not going to have any transport truck spawns

so now ppl will solo logistic trucks?

**Comment by benvalkin** [comment]
> so now ppl will solo logistic trucks?

Well, it has already been suggested that transport trucks are never used. If you agree with this statement, then I'm not sure why you think people would solo logis more if transport trucks are removed.

**Comment by UsernameIsUnavailible** [comment]
so next season, no transport trucks but instead more humvees or/and unarmed humvees?

**Comment by benvalkin** [comment]
> so next season, no transport trucks but instead more humvees or/and unarmed humvees?

sure
