### ISSUE TITLE
Migrate old translations to new system

### ISSUE THREAD

**Issue by DanielWillett** [UncreatedStaff/UncreatedWarfare#8]
All 1000+ translations need to be rewritten for the new system.

**Comment by Entity645** [comment]
Would the translation be easier than the almost html that is the localization file.

**Comment by DanielWillett** [comment]
Yes, this is what the file looks like right now.
![image](https://user-images.githubusercontent.com/12886600/179667264-b4c4af40-5c91-4f19-b341-8a8e10d5249f.png)
