### ISSUE TITLE
Special kits for the insurgency game mode if/when it's ever fixed

### ISSUE THREAD

**Issue by Host69** [UncreatedStaff/UncreatedWarfare#82]
Just special kits to make insurgency more different which can only be used on the side guarding the weapon caches, they could be on the lower left side wall of the barracks and only used during insurgency and disabling the main kits used on all other rounds for the side defending the cache same with custom kits if special insurgency kits were added because this would cause extreme unbalancing issues on both sides if custom kits were allowed during this game mode, and for ideas on the kits just look at a insurgent faction from project reality like the African resistance fighters or something

**Comment by UsernameIsUnavailible** [comment]
special kits for each team would make it even more difficult to create (unless 420 or/and blazing knows an easy way to do so)

**Comment by Host69** [comment]
It wouldn't be difficult, example both team would have the same insurgency kits, but only the people defending the caches would get access to those kits, while the other team just uses kits they would use on any gamemode

**Comment by HamzaXSniper** [comment]
What type of "special kits" are you thinking of?

**Comment by Host69** [comment]
Like stuff insurgents would have, look at project reality insurgency faction kits , that's basically what I'm talking about

**Comment by benvalkin** [comment]
Because we can have rotatable gamemodes but not rotatable factions every round, we can't really have unique kits just for Insurgency. That being said, next season's factions wouldn't fit the aesthetic of an irregular army at all, so unique kits for the Insurgency gamemode doesn't make sense.
