### ISSUE TITLE
Attachements Suggestion(s)

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [UncreatedStaff/UncreatedWarfare#85]
Currently we really, _really_ lack any picatinny sights for AK styled weapons. More sights like PKA, PK-AS, PKS-07.
What would also be a idea is having adaptor rails for picatinny to rails "module" to craft a sight (view example
![Schermafbeelding 2022-08-17 022859](https://user-images.githubusercontent.com/101991669/185007778-70e7454a-a2b2-4894-a1b2-d76bd8f309cf.png)
)

**Comment by UsernameIsUnavailible** [comment]
For example an AK-105 with adapted halo would look like this: 
![image](https://user-images.githubusercontent.com/101991669/185008631-f7b2e647-e2d8-4d8d-a3e3-922684f68303.png)

**Comment by benvalkin** [comment]
I'd prefer not to do this because I like having a AK optics and Rail optics be two separate classes

**Comment by UsernameIsUnavailible** [comment]
> I'd prefer not to do this because I like having a AK optics and Rail optics be two separate classes

Theres like only two sights for AKs.. Having seperate classes for each is just unfair as all rail mounted weapons have more then 5 sights..

**Comment by benvalkin** [comment]
> > I'd prefer not to do this because I like having a AK optics and Rail optics be two separate classes
> 
> Theres like only two sights for AKs.. Having seperate classes for each is just unfair as all rail mounted weapons have more then 5 sights..
We'll make more dedicated ones in the future
