### ISSUE TITLE
Better pings/communication

### ISSUE THREAD

**Issue by Kazumiiiiiiiiii** [UncreatedStaff/UncreatedWarfare#91]
When you mark a target/player, the icon is the same size regardless of distance, which can get really confusing when you don't have a line of sight. Is it possible to get a distance indicator over the mark? 
Or another way could be that every player on the team gets a different spot message, so it includes the distance to spot when it says "xxx spotted xxx near xxx *(xxm)"  using something similar to what the /msg plugin does.

Also, there's a lot of frustration when you're shooting or getting shot by someone and your teammates don't notice. Can we get an exclamation mark (similar to a pinged target) over our heads when we shoot/get shot at by an enemy? It'll help a lot with cohesiveness during fights.

tyty

**Comment by DanielWillett** [comment]
The chat distance is possible, theres not really a good way to add text to effects. The action menu will solve a lot of the problems you bring up in the second paragraph. #14
