### ISSUE TITLE
Team Shuffle

### ISSUE THREAD

**Issue by Nightshadow935** [UncreatedStaff/UncreatedWarfare#98]
so, I understand the purpose of giving people choice. some people like the MEC guns, some people like the USA guns. though the more I play the server the more I notice something obvious: balance. it doesn't exist

everyone who starts, almost all new players, go to USA first. then, once they get stomped, or get more experienced, they go to MEC. sure, there are exceptions to this, though from what I have seen this is what happens almost all the time in matches. something seriously needs to be done about this

when I play MEC, I get bored quickly, as the game is just a rush to capture, as the USA team doesn't bother, or is unable to defend properly. when I play USA, the entire team is unable to coordinate and work well, and instead insists on making an FOB at Gayal Appartments, when Beach landing is currently being captured

some sort of auto balance and auto assign feature needs to be added

one idea of mine, and, keep in mind, I have literally 0 coding experience/knowledge, so I don't know the possibility or viability of this, however, perhaps the first 10 players to each team are allowed to be chosen. for example: start of a new game. 20 players total are able to choose MEC or USA. decided either by random choice, or by who can click fast enough. everyone else gets auto assigned to either MEC or USA. I could see this leading to some people simply "not playing this round" since they are stubborn and only want to play a certain team, though, I would like to hear other ideas, not just from staff but from others. I feel the server needs some kind of auto balance to ensure that one team isn't always getting killed, and one team isn't just sweeping the game. literally today, had a game that lasted a total of 7 minutes, 32 seconds. when games like that are happening, balance isn't really there

**Comment by HamzaXSniper** [comment]
Forcing players to play a certain team will definitely discourage them from playing, even if in short time 1 team could be winning but in the long time both teams have similar wins/loses. I agree some balance should be made but its really up to the players what team they would play.

**Comment by Nightshadow935** [comment]
true, while it would be difficult to make it so people willingly play on the team they don't want, there needs to be something done. as I said, the amount of times USA loses horribly and MEC stomps them is embarrassing. I don't even need to be on the server right now to tell you MEC is likely winning whatever fight is happening

**Comment by HamzaXSniper** [comment]
Mec gets stomped on the same amount as usa does when the good players arent online on mec/ only the good usa members are online. The stats posted a couple months ago show that.
![image](https://user-images.githubusercontent.com/109538125/186311297-c8b4353a-a91b-43d2-a2a5-a3aaad470cfb.png)

**Comment by Nightshadow935** [comment]
true, when its not peak hours and the regulars aren't on, MEC has a chance to get killed. though when *EVERY* good player flocks to MEC and spam clicks it like their life depends on it (because their on sanity mostly does) then saying "ok, you need to go to the other team now" doesn't seem as bad
again, I get it. MEC gets stomped just as much. but those statistics are overall statistics. over the course of 1000 games, everything evens out for the most part. look at the statistics of the past 10, or 50 games though, and a different story often is seen
regardless, you get my point I assume

**Comment by HamzaXSniper** [comment]
I see your point about this but forcing players to a specific team is not the way to go. I also do believe that balance should be a priority but not in the way you suggested, I have no ideas in my head right now but there is definitely a fix to this wether its more known factions to divide players equally or made up ones to remove bias.

**Comment by s-worce** [comment]
Bluntly no matter how hard you try you aren't gonna balance the teams in the server because of the overall stupidity of the playerbase unless you plan on having someone hand pick teams every round. And don't even think about trying to artificially balance with gun and vehicle changes. The only semi-viable way the server will become "balanced" is if everyone is taught how to use their 4 braincells and read chat, but realistically that won't happen. If you want balance,  learn how to carry your team.

**Comment by HamzaXSniper** [comment]
Make uncreated an application only server ong?

**Comment by Nightshadow935** [comment]
I know Hazma, I know. though something needs to be done, as you said. what that is, I don't know. I gave an idea that came to my head then and there. and Worce, yes, I get it, there is no way to balance the guns and vehicles more. because if one team has more powerful things, then the good players will all go there, and people will complain. the thing is, one person cant change the outcome of a match most games. maybe once in awhile, but not always. something with team balance needs to be done to allow for skill based matching for the teams. otherwise its just the same game over and over again...

game starts, MEC captures two, three objectives, and USA is just finishing capturing their first as MEC is now capturing their second to last objective. game ends quickly, and the people who are satisfied with "a proper fight" and "a true struggle" are left to just be upset and annoyed

**Comment by HamzaXSniper** [comment]
Most of the active "good" players play on mec, which has a disadvantage in the matter of equipment, But braincells play a huge difference if usa players are busy playing wannabe navy seal and not capturing, Its their fault.

**Comment by s-worce** [comment]
Skill based matchmaking is stupid don't even try, this isn't some competitive title. And bluntly 1 player can carry a game barring the extremes.

**Comment by Nightshadow935** [comment]
"But braincells play a huge difference if usa players are busy playing wannabe navy seal and not capturing, Its their fault."

and thats what im saying. MEC teams are filled with the skilled players. though USA is filled with the non skilled players. because people who are skilled only play MEC, and something needs to be done to try to change this so skilled players are on both teams

**Comment by s-worce** [comment]
Have you considered not being a smoothbrain and raising the collective 4 iq of players instead of malding about it. All forced balancing ever does is piss more people off.

**Comment by Nightshadow935** [comment]
Worce, im trying to have a proper, serious conversation about this sort of thing. asking staff for their suggestions and ideas about it. im not after sarcasm and back hand comments

**Comment by HamzaXSniper** [comment]
He got a point though.

**Comment by Nightshadow935** [comment]
yea. I know. forced balancing upsets people. though it was a suggestion I made on the spot. maybe there are other ideas that people can come up with in an actual serious conversation. perhaps rewarding those who play on USA and MEC with something. i dont know what but something. a lot of the issue i have coming up with ideas is the fact that there are some people who are swimming in so much credits it makes credits a worthless currency, and XP just as much

**Comment by s-worce** [comment]
Yeah, educating the current player base or working on your skill issue and carrying the team yourself.

**Comment by benvalkin** [comment]
We never had this problem last season with US and Russia, I think the problem is that skilled players keep joining MEC because it has more exciting stuff. I'm hoping this will change next season with different factions, but for now could we potentially add a team shuffle feature that kicks in after one team has won too many rounds in a row?

**Comment by UsernameIsUnavailible** [comment]
> We never had this problem last season with US and Russia, I think the problem is that skilled players keep joining MEC because it has more exciting stuff. I'm hoping this will change next season with different factions, but for now could we potentially add a team shuffle feature that kicks in after one team has won too many rounds in a row?

I "warned" before S2 release that taking US again would cause this/make it boring

**Comment by Nightshadow935** [comment]
> We never had this problem last season with US and Russia, I think the problem is that skilled players keep joining MEC because it has more exciting stuff. I'm hoping this will change next season with different factions, but for now could we potentially add a team shuffle feature that kicks in after one team has won too many rounds in a row?

This. This is exactly what I would be after. A team shuffle after like, 3-5 wins in a row would be amazing and very well balanced. If a certain team is winning that much in a row it most likely isn’t coincidence
